# Generated by Django 3.0.4 on 2024-02-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='fecha_cracion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='fecha_cracion',
            new_name='fecha_creacion',
        ),
    ]
